#!/usr/bin/env python3
"""Generate our original equalizer icon and its embedded bytes (stdlib only)."""
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]


def chunk(kind, data):
    return struct.pack('!I', len(data)) + kind + data + struct.pack('!I', zlib.crc32(kind + data))


def generate():
    size = 64
    rows = bytearray()
    for y in range(size):
        rows.append(0)  # PNG filter: none
        for x in range(size):
            bar = any(left <= x < left + 6 and 32 - height <= y < 32 + height
                      for left, height in ((12, 9), (23, 19), (34, 14), (45, 23)))
            rows.extend((70, 220, 190) if bar else (18, 32, 46))
    png = (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('!2I5B', size, size, 8, 2, 0, 0, 0))
           + chunk(b'IDAT', zlib.compress(rows, 9)) + chunk(b'IEND', b''))
    (ROOT / 'upnp/icon.png').write_bytes(png)
    lines = [', '.join(f'0x{b:02x}' for b in png[i:i + 12]) for i in range(0, len(png), 12)]
    (ROOT / 'upnp/icon.h').write_text('// Generated by scripts/make-icon.py; original project artwork.\n'
                                    'constexpr unsigned char iconPng[] = {\n    '
                                    + ',\n    '.join(lines) + '\n};\n')


if __name__ == '__main__':
    generate()
