"""Adapt the pinned upstream source without changing the squeezelite submodule."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
text=(root/'squeezelite/slimproto.c').read_text()
changes={
    '\t\t\tstatus.output_full = _buf_used(outputbuf);': '\t\t\tSONOS_STATUS();\n\t\t\tstatus.output_full = _buf_used(outputbuf);',
    'if (output.state == OUTPUT_RUNNING && !sentSTMu &&': 'if (output.state == OUTPUT_RUNNING && SONOS_DRAINED() && !sentSTMu &&',
    'if (output.state == OUTPUT_RUNNING && !sentSTMo &&': 'if (output.state == OUTPUT_RUNNING && SONOS_DRAINED() && !sentSTMo &&',
}
for old,new in changes.items():
    if text.count(old)!=1: raise SystemExit('Pinned squeezelite adaptation anchor changed: '+old)
    text=text.replace(old,new)
(root/'slimproto_sonos_impl.h').write_text('// Generated by scripts/prepare-sonos-slimproto.py; do not edit.\n'+text)
